project_id = "fbtzmjmrugsuegxscujj"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.claim-session]
verify_jwt = false


[functions.verify-admin]
verify_jwt = false

[functions.update-tenant]
verify_jwt = false